/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import analexico.AFD;
import analexico.AFN;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Raul
 */
public class AppGENLEX extends javax.swing.JInternalFrame {

    /**
     * Creates new form AppGENLEX
     */
    
    private ArrayList<AFN> listAFN;
    
    public AppGENLEX() {
        initComponents();
        listAFN = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        popUp = new javax.swing.JPopupMenu();
        ItemCerrEpsilon = new javax.swing.JMenuItem();
        ItemMover = new javax.swing.JMenuItem();
        ItemIrA = new javax.swing.JMenuItem();
        buttonCreaBasico = new javax.swing.JButton();
        buttonUnion = new javax.swing.JButton();
        buttonConcat = new javax.swing.JButton();
        buttonCerrPos = new javax.swing.JButton();
        buttonCerrKlin = new javax.swing.JButton();
        buttonOpc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAFN = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListEstados = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listEdosAcept = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListAlfabeto = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listTrans = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFEdoIni = new javax.swing.JTextField();
        btnUnionEspecial = new javax.swing.JButton();
        toAFDButton = new javax.swing.JButton();

        ItemCerrEpsilon.setText("Cerradura Epsilon");
        ItemCerrEpsilon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCerrEpsilonActionPerformed(evt);
            }
        });
        popUp.add(ItemCerrEpsilon);

        ItemMover.setText("Mover");
        ItemMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMoverActionPerformed(evt);
            }
        });
        popUp.add(ItemMover);

        ItemIrA.setText("Ir A");
        ItemIrA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIrAActionPerformed(evt);
            }
        });
        popUp.add(ItemIrA);

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCreaBasico.setText("Crea Basico");
        buttonCreaBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreaBasicoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCreaBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 42, -1, -1));

        buttonUnion.setText("Union");
        buttonUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUnionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUnion, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 42, -1, -1));

        buttonConcat.setText("Concatenacion");
        buttonConcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConcatActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 42, -1, -1));

        buttonCerrPos.setText("Cerradura +");
        buttonCerrPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrPosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCerrPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 42, -1, -1));

        buttonCerrKlin.setText("Cerradura K");
        buttonCerrKlin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrKlinActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCerrKlin, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 42, -1, -1));

        buttonOpc.setText("Opcion");
        buttonOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpcActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        jLabel2.setText("AFNs");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        listaAFN.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaAFNValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaAFN);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));

        jLabel3.setText("Alfabeto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, popUp, org.jdesktop.beansbinding.ObjectProperty.create(), ListEstados, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        ListEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListEstadosMouseReleased(evt);
            }
        });
        ListEstados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListEstadosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(ListEstados);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 110, 130));

        jLabel4.setText("Estados");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jScrollPane5.setViewportView(listEdosAcept);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 100, 130));

        jLabel6.setText("Edos Acept");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jScrollPane1.setViewportView(ListAlfabeto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 90, 130));

        jScrollPane4.setViewportView(listTrans);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 220, 130));

        jLabel5.setText("Transiciones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        jLabel7.setText("Estado inicial :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        TFEdoIni.setEditable(false);
        getContentPane().add(TFEdoIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 130, -1));

        btnUnionEspecial.setText("Union Especial");
        btnUnionEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnionEspecialActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnionEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        toAFDButton.setText("Generar AFD");
        toAFDButton.setEnabled(false);
        toAFDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAFDButtonActionPerformed(evt);
            }
        });
        getContentPane().add(toAFDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreaBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreaBasicoActionPerformed
        // TODO add your handling code here:
        
        AFN nvo = new AFN();
//        char[] chararray = JOptionPane.showInputDialog(this, "Introduce Caracter", "AFN Nuevo Basico", JOptionPane.QUESTION_MESSAGE).toCharArray();
        ViewCreaBasico vcb = new ViewCreaBasico(null, true);
        vcb.setVisible(true);
        nvo.CreaBasico(vcb.carMax,vcb.carMin,vcb.getRange());
        vcb.dispose();
        listAFN.add(nvo);
        llenarList();
    }//GEN-LAST:event_buttonCreaBasicoActionPerformed

    private void buttonUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUnionActionPerformed
        // TODO add your handling code here:
        if (listAFN.size() <= 1) {
            JOptionPane.showMessageDialog(this, "Necesitas crear otro automata mas", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] arreglo = listAFN.toArray();
            AFN af1 = (AFN) JOptionPane.showInputDialog(this, "Selecciona el primer AFN(Sobre este se hara la operacion)", "Union", JOptionPane.PLAIN_MESSAGE, null, arreglo, arreglo[0]);
            AFN af2 = (AFN) JOptionPane.showInputDialog(this, "Selecciona el segundo AFN", "Union", JOptionPane.PLAIN_MESSAGE, null, arreglo, arreglo[0]);
            af1.Union(af2);
            listAFN.remove(af2);
        }
        llenarList();
    }//GEN-LAST:event_buttonUnionActionPerformed

    private void buttonConcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConcatActionPerformed
        // TODO add your handling code here:
        if (listAFN.size() <= 1) {
            JOptionPane.showMessageDialog(this, "Necesitas crear otro automata mas", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] arreglo = listAFN.toArray();
            AFN af1 = (AFN) JOptionPane.showInputDialog(this, "Selecciona el primer AFN(Sobre este se hara la operacion)", "Concatenacion", JOptionPane.PLAIN_MESSAGE, null, arreglo, arreglo[0]);
            AFN af2 = (AFN) JOptionPane.showInputDialog(this, "Selecciona el segundo AFN", "Concatenacion", JOptionPane.PLAIN_MESSAGE, null, arreglo, arreglo[0]);
            af1.Concatenacion(af2);
            listAFN.remove(af2);
        }
        llenarList();
    }//GEN-LAST:event_buttonConcatActionPerformed

    private void buttonCerrPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrPosActionPerformed
        // TODO add your handling code here:
        if (listAFN.size() < 1) {
            JOptionPane.showMessageDialog(this, "Necesitas crear un automata", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] arreglo = listAFN.toArray();
            AFN af1 = (AFN) JOptionPane.showInputDialog(this, "Selecciona el AFN(Sobre este se hara la operacion)", "Cerradura Positiva", JOptionPane.PLAIN_MESSAGE, null, arreglo, arreglo[0]);
            af1.CerraduraPos();
        }
        llenarList();
    }//GEN-LAST:event_buttonCerrPosActionPerformed

    private void buttonCerrKlinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrKlinActionPerformed
        // TODO add your handling code here:
        if (listAFN.size() < 1) {
            JOptionPane.showMessageDialog(this, "Necesitas crear un automata", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] arreglo = listAFN.toArray();
            AFN af1 = (AFN) JOptionPane.showInputDialog(this, "Selecciona el AFN(Sobre este se hara la operacion)", "Cerradura Klin", JOptionPane.PLAIN_MESSAGE, null, arreglo, arreglo[0]);
            af1.CerraduraKlin();
        }
        llenarList();
    }//GEN-LAST:event_buttonCerrKlinActionPerformed

    private void buttonOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpcActionPerformed
        // TODO add your handling code here:
        if (listAFN.size() < 1) {
            JOptionPane.showMessageDialog(this, "Necesitas crear un automata", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] arreglo = listAFN.toArray();
            AFN af1 = (AFN) JOptionPane.showInputDialog(this, "Selecciona el AFN(Sobre este se hara la operacion)", "Cerradura Klin", JOptionPane.PLAIN_MESSAGE, null, arreglo, arreglo[0]);
            af1.Opc();
        }
        llenarList();
    }//GEN-LAST:event_buttonOpcActionPerformed

    private void listaAFNValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaAFNValueChanged
        // TODO add your handling code here:
        AFN selected = (AFN) listaAFN.getSelectedValue();
        llenarListaEdos(selected.getEstados());
        llenarListaAlfabeto(selected.getAlfabeto());
        llenarListaEdosAcept(selected.getEdosAcept());
        TFEdoIni.setText(selected.getInicial().toString());
    }//GEN-LAST:event_listaAFNValueChanged

    private void ListEstadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListEstadosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ListEstadosMouseReleased

    private void ListEstadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListEstadosValueChanged
        // TODO add your handling code here:
        AFN.Estado e = (AFN.Estado) ListEstados.getSelectedValue();
        llenarListaTransiciones(e.getTransiciones());
    }//GEN-LAST:event_ListEstadosValueChanged

    private void btnUnionEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionEspecialActionPerformed
        // TODO add your handling code here:
        AFN res = new AFN();
        for (AFN a : listAFN) {
            String token = JOptionPane.showInputDialog("Token para AFN" + a.getIdAFN());
            HashSet<AFN.Estado> lista = a.getEdosAcept();
            for (AFN.Estado e : lista) {
                e.setToken(Integer.parseInt(token));
            }
        }
        res = res.UnionEspecial(listAFN);
        listAFN.clear();
        listAFN.add(res);
        toAFDButton.setEnabled(true);
        llenarList();
    }//GEN-LAST:event_btnUnionEspecialActionPerformed

    private void toAFDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAFDButtonActionPerformed
        // TODO add your handling code here:
        AFN a = listAFN.get(0);
        AFD afd = a.toAFD();
        ArrayList<int[]> trans = afd.getTransiciones();
        JFileChooser jfc = new JFileChooser(".");
        jfc.setDialogTitle("Guardar");
        int status = jfc.showSaveDialog(this);
        if(status == JFileChooser.APPROVE_OPTION){
            afd.save(jfc.getSelectedFile());
        }
    }//GEN-LAST:event_toAFDButtonActionPerformed

    private void ItemCerrEpsilonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCerrEpsilonActionPerformed
        // TODO add your handling code here:
        List<AFN.Estado> edos = ListEstados.getSelectedValuesList();
        HashSet<AFN.Estado> conj = new HashSet<>();
        for (AFN.Estado e : edos) {
            conj.add(e);
        }
        AFN aux = (AFN) listaAFN.getSelectedValue();
        HashSet<AFN.Estado> res = aux.CerraduraEpsilon(conj);
        JOptionPane.showMessageDialog(this, "La cerradura epsilon de " + edos + "es: \n" + res, "Cerradura Epsilon", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ItemCerrEpsilonActionPerformed

    private void ItemMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMoverActionPerformed
        // TODO add your handling code here:
        AFN aux = (AFN) listaAFN.getSelectedValue();
        Object[] arrAlf = aux.getAlfabeto().toArray();
        char s = (char) JOptionPane.showInputDialog(this, "Selecciona el caracter para la operacion", "Mover", JOptionPane.PLAIN_MESSAGE, null, arrAlf, arrAlf[0]);
        List<AFN.Estado> edos = ListEstados.getSelectedValuesList();
        HashSet<AFN.Estado> conj = new HashSet<>();
        for (AFN.Estado e : edos) {
            conj.add(e);
        }

        HashSet<AFN.Estado> res = aux.Mover(conj, s);
        JOptionPane.showMessageDialog(this, "Mover " + edos + "con: " + s + "\n" + res, "Mover", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ItemMoverActionPerformed

    private void ItemIrAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIrAActionPerformed
        // TODO add your handling code here:
        AFN aux = (AFN) listaAFN.getSelectedValue();
        Object[] arrAlf = aux.getAlfabeto().toArray();
        char s = (char) JOptionPane.showInputDialog(this, "Selecciona el caracter para la operacion", "Ir A", JOptionPane.PLAIN_MESSAGE, null, arrAlf, arrAlf[0]);
        List<AFN.Estado> edos = ListEstados.getSelectedValuesList();
        HashSet<AFN.Estado> conj = new HashSet<>();
        for (AFN.Estado e : edos) {
            conj.add(e);
        }
        HashSet<AFN.Estado> res = aux.Ir_A(conj, s);
        JOptionPane.showMessageDialog(this, "Ir A " + edos + "con " + s + ":\n" + res, "Ir A", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ItemIrAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCerrEpsilon;
    private javax.swing.JMenuItem ItemIrA;
    private javax.swing.JMenuItem ItemMover;
    private javax.swing.JList ListAlfabeto;
    private javax.swing.JList ListEstados;
    private javax.swing.JTextField TFEdoIni;
    private javax.swing.JButton btnUnionEspecial;
    private javax.swing.JButton buttonCerrKlin;
    private javax.swing.JButton buttonCerrPos;
    private javax.swing.JButton buttonConcat;
    private javax.swing.JButton buttonCreaBasico;
    private javax.swing.JButton buttonOpc;
    private javax.swing.JButton buttonUnion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList listEdosAcept;
    private javax.swing.JList listTrans;
    private javax.swing.JList listaAFN;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JButton toAFDButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
    private void llenarList() {
        DefaultListModel<AFN> modelo = new DefaultListModel<>();
        for (int i = 0; i < listAFN.size(); i++) {
            modelo.addElement(listAFN.get(i));
        }
        listaAFN.setModel(modelo);
    }

    private void llenarListaEdos(HashSet<AFN.Estado> estados) {
        DefaultListModel<AFN.Estado> modelo = new DefaultListModel<>();
        estados.stream().forEach((e) -> {
            modelo.addElement(e);
        });
        ListEstados.setModel(modelo);
    }

    private void llenarListaAlfabeto(HashSet<Character> alfabeto) {
        DefaultListModel<Character> modelo = new DefaultListModel<>();
        alfabeto.stream().forEach((e) -> {
            modelo.addElement(e);
        });
        ListAlfabeto.setModel(modelo);
    }

    private void llenarListaTransiciones(HashSet<AFN.Transicion> transiciones) {
        DefaultListModel<AFN.Transicion> modelo = new DefaultListModel<>();
        transiciones.stream().forEach((t) -> {
            modelo.addElement(t);
        });
        listTrans.setModel(modelo);
    }

    private void llenarListaEdosAcept(HashSet<AFN.Estado> edosAcept) {
        DefaultListModel<AFN.Estado> modelo = new DefaultListModel<>();
        edosAcept.stream().forEach((e) -> {
            modelo.addElement(e);
        });
        listEdosAcept.setModel(modelo);
    }

}
