/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import analexico.AFD;
import analexico.AnalizadorLex;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Raul
 */
public class ViewAnaLexico extends javax.swing.JInternalFrame {
    
    private AnalizadorLex a ;
    
    /**
     * Creates new form ViewAnaLexico
     * @param afd
     */
    public ViewAnaLexico(AFD afd) {
        a = new AnalizadorLex(afd);
        initComponents();
        int[] ai = afd.getTransiciones().get(0);
        Object[][] rowData = new Object[ai.length][afd.getTransiciones().size()];
        String[] columnNames = new String[afd.getAlfabeto().length + 1];
        for(int i = 0; i < afd.getAlfabeto().length; i++){
            columnNames[i] = afd.getAlfabeto()[i].toString();
        }
        columnNames[afd.getAlfabeto().length] = "Token";
        jTable1 = new JTable(rowData, columnNames);
        jTable1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CadTF = new javax.swing.JTextField();
        getTokenButton = new javax.swing.JButton();
        returnTokenButton = new javax.swing.JButton();
        getLexemaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Escribe la cadena a analizar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        getContentPane().add(CadTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, -1));

        getTokenButton.setText("getToken");
        getTokenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTokenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(getTokenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        returnTokenButton.setText("returnToken");
        returnTokenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnTokenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnTokenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        getLexemaButton.setText("getLexema");
        getLexemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLexemaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(getLexemaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getTokenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTokenButtonActionPerformed
        if(a.getCadena() == null){
            a.setCadena(CadTF.getText());
        }
        int tokens = a.getToken();
        JOptionPane.showMessageDialog(this, "La cadena de Tokens es: \n" + tokens);
    }//GEN-LAST:event_getTokenButtonActionPerformed

    private void returnTokenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnTokenButtonActionPerformed
        a.returnToken();
    }//GEN-LAST:event_returnTokenButtonActionPerformed

    private void getLexemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLexemaButtonActionPerformed
        JOptionPane.showMessageDialog(this, "La cadena de Tokens es: \n" + a.getLexema());
    }//GEN-LAST:event_getLexemaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadTF;
    private javax.swing.JButton getLexemaButton;
    private javax.swing.JButton getTokenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton returnTokenButton;
    // End of variables declaration//GEN-END:variables
}
